pre-commit:
  parallel: true
  commands:
    cargo-fmt:
      glob: "*.rs"
      run: rustfmt --edition 2021 --emit files {staged_files}
      stage_fixed: true
    cargo-clippy:
      glob: "*.rs"
      run: cargo clippy -- -D warnings
    check-typos:
      run: typos {staged_files}
