[package]
name = "intmax2-interfaces"
version.workspace = true
edition = "2021"

[dependencies]
plonky2 = { workspace = true }
plonky2_keccak = { workspace = true }
intmax2-zkp = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
anyhow = "1.0.93"
bincode = "1.3.3"
hashbrown = "0.14.5"
async-trait = "0.1.83"
thiserror = "2.0.3"
