on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1

jobs:
  format-check:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: cargo fmt
        run: cargo fmt --check --all
  doc:
    name: doc
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
      - name: Check docs
        run: cargo doc --no-deps
  typos:
    name: typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: typos-action
        uses: crate-ci/typos@master
  clippy:
    name: clippy
    needs: format-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - uses: r7kamura/rust-problem-matchers@v1
      - name: cargo clippy
        run: cargo clippy --tests -- -D warnings -D "clippy::perf" -D "clippy::correctness"
  tests:
    name: tests
    needs: clippy
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      anvil:
        image: ghcr.io/foundry-rs/foundry:latest
        ports:
          - 8545:8545
        options: >-
          --health-cmd="curl -f http://localhost:8545"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          --entrypoint "anvil -- --host 0.0.0.0"
        env:
          ANVIL_IP_ADDR: 0.0.0.0
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest
      - uses: r7kamura/rust-problem-matchers@v1
      - name: Run tests
        run: cargo nextest run --profile ci
